/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hi.jooby;

import static io.restassured.RestAssured.get;
import static org.hamcrest.Matchers.equalTo;
import org.jooby.test.JoobyRule;
import org.testng.annotations.*;

public class AppTest {

    public static JoobyRule app = new JoobyRule(new App());

    @Test
    public void appHasAGreeting() {
        get("/")
                .then()
                .assertThat()
                .body(equalTo("Hello Jooby!"))
                .statusCode(200);
    }
}
