/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hi.jooby;

import hi.jooby.module.SayHiModule;
import org.jooby.Jooby;
import org.jooby.RequestLogger;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.ZoneId;

public class App extends Jooby {

    {
        use("*", new RequestLogger()
            .dateFormatter(ZoneId.of("UTC"))
                .extended()
        );
        use(new SayHiModule());
    }

    public static void main(String[] args) {
        run(App::new, args);
    }
}
